### ISSUE TITLE
Conda Issue when creating the environement

### ISSUE THREAD

**Issue by rth** [FreeDiscovery/FreeDiscovery#125]
When creating the conde environement for `v0.9.1`, the following error was reported on Ubuntu. This might be related to https://github.com/conda/conda/issues/4798 but I haven't been  able to reproduce it so far..

```
conda create -n freediscovery-env --file requirements.txt python=3.6

    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 823, in execute_actions
        plan = plan_from_actions(actions, index)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 358, in plan_from_actions
        plan = inject_UNLINKLINKTRANSACTION(plan, index, prefix)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 320, in inject_UNLINKLINKTRANSACTION
        pfe.prepare()
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 447, in prepare
        for dist in self.link_dists)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 447, in <genexpr>
        for dist in self.link_dists)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 380, in make_actions_for_dist
        first_writable_cache = PackageCache.first_writable()
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 168, in first_writable
        return cls.all_writable(pkgs_dirs)[0]
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 179, in all_writable
        "%s" % context.pkgs_dirs)
    TypeError: not all arguments converted during string formatting
```

**Comment by rth** [comment]
This was the result of installing minoconda with `sudo` (which results in a `$HOME/miniconda`) folder with the wrong permission. A note should be added about it in the docs...
