### ISSUE TITLE
Error -- running FreeDiscovery server

### ISSUE THREAD

**Issue by jonnymacuser** [FreeDiscovery/FreeDiscovery#157]
root@debian:/home/debian/miniconda3/bin# ./freediscovery run
================================================================================
                     FreeDiscovery server
                      (version 1.1.2)
================================================================================
 * Started on Sat Jul  8 11:30:24 2017
 * CACHE_DIR: /home/debian/miniconda3/freediscovery_shared [EXISTING]
 * LOG_FILE: /home/debian/miniconda3/freediscovery_shared/freediscovery-backend.log
Traceback (most recent call last):
  File "./freediscovery", line 11, in <module>
    sys.exit(main())
  File "/home/debian/miniconda3/lib/python3.6/site-packages/freediscovery/__main__.py", line 313, in main
    args.func(args)
  File "/home/debian/miniconda3/lib/python3.6/site-packages/freediscovery/__main__.py", line 68, in _run
    app = fd_app(cache_dir, df_config)
  File "/home/debian/miniconda3/lib/python3.6/site-packages/freediscovery/server/app.py", line 120, in fd_app
    docs.register(resource_el, endpoint=ressource_name)
  File "/home/debian/miniconda3/lib/python3.6/site-packages/flask_apispec/extension.py", line 74, in register
    paths = self.resource_converter.convert(target, endpoint, blueprint)
  File "/home/debian/miniconda3/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 25, in convert
    return [self.get_path(rule, target) for rule in rules]
  File "/home/debian/miniconda3/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 25, in <listcomp>
    return [self.get_path(rule, target) for rule in rules]
  File "/home/debian/miniconda3/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 35, in get_path
    for method, view in six.iteritems(operations)
  File "/home/debian/miniconda3/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 36, in <dictcomp>
    if method.lower() in (set(VALID_METHODS) - {'head'})
  File "/home/debian/miniconda3/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 48, in get_operation
    'parameters': self.get_parameters(rule, view, docs, parent),
  File "/home/debian/miniconda3/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 71, in get_parameters
    **options
TypeError: fields2parameters() got an unexpected keyword argument 'dump'

**Comment by jonnymacuser** [comment]
Installed python3, miniconda, anaconda, etc.

**Comment by rth** [comment]
@jonnymacuser Thaks for the report! This is due to breaking change in the apispec 0.20 (https://github.com/jmcarp/flask-apispec/issues/41). The solution is to downgrade to apispec 0.19 with,
```
conda install  apispec==0.19.0
```
We'll update the `requirements.txt` to make sure earlier versions of apispec don't get installed for now...

**Comment by rth** [comment]
@jonnymacuser A better solution is to install the latest  `flask-apispec` 0.4.0 (recently released on conda-forge), which fixes this issue,
```py
conda install flask-apispec
```
I'm closing this issue. Please reopen it, if you still experience difficulties with the installation.
