### ISSUE TITLE
Compatibility issues with marshmallow

### ISSUE THREAD

**Issue by rth** [FreeDiscovery/FreeDiscovery#181]
Following issue has been reported when running FreeDiscovery 1.3.1 on Windows 7,
```pytb
$ python .\freediscovery run
Traceback (most recent call last):
  File ".\freediscovery", line 11, in <module>
    load_entry_point('freediscovery==1.3.1', 'console_scripts', 'freediscovery')()
  File "Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2322, in load
    return self.resolve()
  File "Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "Anaconda3\lib\site-packages\freediscovery\__main__.py", line 11, in <module>
    from .server import fd_app
  File "Anaconda3\lib\site-packages\freediscovery\server\__init__.py", line 7, in <module>
    from .app import fd_app
  File "Anaconda3\lib\site-packages\freediscovery\server\app.py", line 7, in <module>
    from flask_apispec import FlaskApiSpec
  File "Anaconda3\lib\site-packages\flask_apispec\__init__.py", line 4, in <module>
    from flask_apispec.extension import FlaskApiSpec
  File "Anaconda3\lib\site-packages\flask_apispec\extension.py", line 6, in <module>
    from apispec.ext.marshmallow import MarshmallowPlugin
ImportError: cannot import name 'MarshmallowPlugin'
```

**Comment by rth** [comment]
I can reproduce it on linux, the issue seems to be that `flask-apispec >5.0` is not compatible with apispec <0.20 , and the conda-forge package apispec does not correctly reflect that. While in freediscovery we currently require apispec <0.20. 

A temporary solution, could be to run,
```
conda install "flask-apispec <0.5.0" "apispec <0.20.0"
```

Will apply the fix on the freediscovery conda package.

**Comment by rth** [comment]
Closing as fixed in https://github.com/conda-forge/freediscovery-feedstock/pull/7 , please comment if this doesn't fix it.
